### ISSUE TITLE
Seed is different from what webpage says.

### ISSUE THREAD

**Issue by fbianco32** [Cr4xy/noita-seed-tool#1]
Im running seed 2542041883, in the website it says itll have a snow flask and first shift is lava to pea soup, after testing ingame i start with slime flask and first shift is worm blood to normal blood. Noita is April Build 23 2021

**Comment by Cr4xy** [comment]
The highest allowed seed is 2147483645. I made a commit that should cap the seed at that number.

Update: It seems that noita allows you to set this seed, but with some errors: 
![image](https://user-images.githubusercontent.com/6566889/130509915-cf42ada4-bd73-41a3-89b1-601d07cf73ca.png)

The issue seems to be in the random algorithm wasm module - i will try to replace my implementation with the one from https://github.com/kaliuresis/noa

**Comment by Cr4xy** [comment]
I replaced the wasm module with kaliuresis' version, it seems to be working.
