### ISSUE TITLE
Question about reverse-engineering

### ISSUE THREAD

**Issue by TwoAbove** [Cr4xy/noita-seed-tool#2]
Hey! Very awesome project!

I have a question about how you got all of this information out of the game.
What did you look at to get the algos for perks, biomes, etc? Did you decompile the executable, or is there a simpler way of doind it? 

Thanks!

**Comment by Cr4xy** [comment]
Thank you!

The main part is the random algorithm; I used ghidra and x64dbg to reconstruct the random algorithm in C++.
Later I randomly found a way better version of the noita algorithm by kaliuresis and used that, because my version still had some bugs and also required simd.

Other than that it is basically taking the existing Lua scripts of the game and converting them to JavaScript.

**Comment by TwoAbove** [comment]
Thanks for the answer! I didn't even think about looking at the Lua of the game :smh:

**Comment by Cr4xy** [comment]
Feel free to ask further questions in Discord if you want!

**Comment by GhostDog98** [comment]
@Cr4xy Could you please provide a link to Kaliuresis's algo? I can't find such a thing on their github page, the closest I can find is their 11 orb program, did you simply take the code from that?

**Comment by Cr4xy** [comment]
@GhostDog98 Yeah, basically. I removed the search code for the orbs and added a few more functions (`ProceduralRandomf`, `ProceduralRandomi`) that are just small helpers to make to lua code easier to port. Links: https://github.com/kaliuresis/noa/blob/main/src/noita_random.cpp
https://github.com/Cr4xy/noita-seed-tool/blob/master/lib/src/noita_random.cpp
